export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/home',
  ADD_CUSTOMER: '/addCustomer',
  ADD_ITEM: '/addItem',
  ADD_ITEM_GROUP: '/addItemgroup',
  ADD_TASK: '/addTask',
  ADD_TASK_GROUP: '/addTaskgroup',
  ADD_USER: '/addUser',
  ADD_USER_GROUP: '/addUsergroup',
  ADD_ORDER: '/addOrder',
  ADD_ORDER_V2: '/addOrder1',
  ALL_BILLS: '/allBills',
  ORDER_KANBAN: '/order-kanban',
  ADD_ENQUIRY: '/addEnquiry',
  ADD_NOTE: '/addNote',
  PAYMENT_REPORT: '/paymentReport',
  PRIORITY_REPORT: '/priorityReport',
  ADD_PAYABLE: '/addPayable',
  ADD_RECEIVABLE: '/addRecievable',
  ALL_TRANSACTION: '/allTransaction',
  ALL_TRANSACTION_1: '/allTransaction1',
  ALL_TRANSACTION_2: '/allTransaction2',
  ATTENDANCE_REPORT: '/attendance-report',
  PENDING_TASKS: '/PendingTasks',
  VENDOR_BILLS: '/vendorBills',
  CUSTOMER_360: '/customer-360',
  FLOW_BUILDER: '/flow-builder',
  WHATSAPP_CLOUD: '/whatsapp-cloud',
  CALL_LOGS: '/calllogs',
  ALL_VENDORS: '/AllVendors',
};

export const ROUTE_ALIASES = {
  ALL_TRANSACTION_1_TYPO: '/alltranscation1',
  ADD_NOTE_LOWER: '/addnote',
  ADD_CUSTOMER_LOWER: '/addcustomer',
  ADD_ITEM_LOWER: '/additem',
  ADD_TASK_LOWER: '/addtask',
  ADD_USER_LOWER: '/adduser',
  ADD_USER_GROUP_LOWER: '/addusergroup',
  ADD_ORDER_V2_LOWER: '/addorder1',
  ALL_BILLS_LOWER: '/allbills',
  ADD_ENQUIRY_LOWER: '/addenquiry',
  PENDING_TASK_LOWER: '/pendingtask',
  ATTENDANCE_REPORT_MIXED: '/Attendance-Report',
  ADD_PAYABLE_TYPO: '/addPayble',
  ALL_TRANSACTION_2_LOWER: '/alltransaction2',
};
