export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/home',
  DASHBOARD: '/dashboard',

  ATTENDANCE: '/attendance',
  ATTENDANCE_REPORT: '/attendance/report',
  ATTENDANCE_REPORT_OLD: '/Attendance-Report',

  TASKS: '/tasks',
  MY_TASKS: '/tasks/my',
  TASKS_NEW: '/tasks/new',
  PENDING_TASKS: '/tasks/pending',
  TASKS_PLANNER: '/planner',
  TASKS_TEAM: '/team',
  TASKS_REVIEW: '/review',

  ENQUIRIES_NEW: '/enquiries/new',

  SEARCH_MOBILE: '/searchMobile',
  MIGRATE_ORDERS: '/orders/migrate',

  ADD_CUSTOMER: '/addCustomer',
  ADD_CUSTOMER_GROUP: '/addCustomergroup',
  ADD_ITEM: '/addItem',
  ADD_ITEM_GROUP: '/addItemgroup',
  ADD_TASK: '/addTask',
  ADD_TASK_GROUP: '/addTaskgroup',
  ADD_PRIORITY: '/addPriority',
  ADD_USER: '/addUser',
  ADD_USER_GROUP: '/addUsergroup',

  ORDERS_NEW: '/orders/new',
  ORDERS_BOARD: '/orders/board',
  BUSINESS_CONTROL: '/business-control',
  DISPATCH_QUEUE: '/dispatch-queue',
  OWNER_DASHBOARD: '/owner-dashboard',
  ORDER_KANBAN: '/orders/board',
  ORDER_UPDATE: '/orders/:id/update',
  DELIVERY_UPDATE: '/delivery/update/:id',
  CUSTOMER_360: '/customers/:id',

  RECEIPT: '/accounts/receipt',
  PAYMENT: '/accounts/payment',
  UPI_COLLECT_PUBLIC: '/upi/collect/:transactionRef',
  UPI_PAYMENT: '/upi-payment',
  ADD_PAYMENT: '/addPayment',
  CASH_LEDGER: '/accounts/cash-ledger',
  BANK_BOOK: '/accounts/bank-book',
  TRIAL_BALANCE: '/accounts/trial-balance',
  FOLLOWUPS: '/accounts/followups',
  ADD_PAYABLE: '/addPayable',
  ADD_RECEIVABLE: '/addRecievable',

  VENDORS: '/vendors',
  VENDOR_DETAILS: '/vendors/:id',

  WHATSAPP: '/whatsapp',
  WHATSAPP_CLOUD: '/whatsapp',
  WHATSAPP_SEND: '/whatsapp/send',
  WHATSAPP_BULK: '/whatsapp/bulk',
  WHATSAPP_LEGACY_HOME: '/WhatsAppHome',
  WHATSAPP_LOGIN_PAGE: '/WhatsAppLogin',
  WHATSAPP_SESSION_PAGE: '/WhatsAppSession',
  WHATSAPP_ADMIN_PANEL: '/WhatsAppAdminPanel',
  WHATSAPP_BROADCAST: '/whatsapp/broadcast',

  REPORTS_ORDERS: '/reports/orders',
  REPORTS_TRANSACTIONS: '/reports/transactions',
  REPORTS_TRANSACTION_1: '/allTransaction1',
  REPORTS_TRANSACTION_2: '/allTransaction2',
  REPORTS_TRANSACTION_3: '/allTransaction3',
  REPORTS_TRANSACTION_4D: '/allTransaction4D',
  ACCOUNT_TRANSACTION: '/accountTransaction',
  REPORTS_CUSTOMERS: '/reports/customers',
  REPORTS_PAYMENTS: '/reports/payments',
  REPORTS_ITEMS: '/reports/items',
  REPORTS_TASKS: '/reports/tasks',
  REPORTS_USERS: '/reports/users',
  REPORTS_VENDORS: '/reports/vendors',
  REPORTS_DELIVERY: '/reports/delivery',
  REPORTS_BILLS: '/allBills',
  REPORTS_PRIORITY: '/priorityReport',
  AGING_REPORT: '/reports/aging',
  PURCHASE_ORDERS: '/purchase-orders',

  // legacy aliases still used in old code
  ADD_ORDER: '/addOrder',
  ADD_ORDER_V2: '/addOrder1',
  ADD_ENQUIRY: '/addEnquiry',
  ADD_NOTE: '/addNote',
  ALL_BILLS: '/allBills',
  ALL_TRANSACTION: '/allTransaction',
  ALL_TRANSACTION_1: '/allTransaction1',
  ALL_TRANSACTION_2: '/allTransaction2',
  ALL_TRANSACTION_3: '/allTransaction3',
  ALL_TRANSACTION_4D: '/allTransaction4D',
  PAYMENT_REPORT: '/paymentReport',
  PRIORITY_REPORT: '/priorityReport',
  VENDOR_BILLS: '/vendorBills',
  ALL_VENDORS: '/AllVendors',
  CALL_LOGS: '/calllogs',
  FLOW_BUILDER: '/flow-builder',
};

export const ROUTE_ALIASES = {
  HOME_ADMIN: '/adminHome',
  HOME_VENDOR: '/vendorHome',
  HOME_OLD: '/home1',
  ADD_NOTE_LOWER: '/addnote',
  ADD_ORDER_V2_LOWER: '/addorder1',
  PENDING_TASK_LOWER: '/pendingtask',
  ATTENDANCE_REPORT_MIXED: '/Attendance-Report',
  ADD_PAYABLE_TYPO: '/addPayble',
  ALL_TRANSACTION_1_TYPO: '/alltranscation1',
  ALL_TRANSACTION_2_LOWER: '/alltransaction2',
  WHATSAPP_LOGIN: '/WhatsAppLogin',
  WHATSAPP_SESSION: '/WhatsAppSession',
  WHATSAPP_ADMIN: '/WhatsAppAdminPanel',
  WHATSAPP_HOME: '/WhatsAppHome',
  WHATSAPP_BROADCAST_PAGE: '/WhatsAppBroadcastPage',
  WHATSAPP_SEND_PAGE: '/WhatsAppSendPage',
  SEARCH_MOBILE_OLD: '/searchmobile',
  PLANNER_OLD: '/Planner',
  TEAM_OLD: '/Team',
  REVIEW_OLD: '/Review',
  FOLLOWUPS_OLD: '/Followups',
};
